linemazzdemo/accounts/urls.py
from django.urls import path
from .views import LoginView, RegisterView, ChangePasswordView, LogoutView

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(), name= 'login'),
    path('logout/', LogoutView.as_view(), name=  'logout'),
    path('register/', RegisterView.as_view(), name= 'register'),
    path('changepassword/', ChangePasswordView.as_view(), name= 'changepassword'),
]

linemazzdemo/chatroom/urls.py
from django.urls import path, include

from .views import ChatRoomView
from .api import get_message, get_lazy_message, send_message

app_name = "chat"

urlpatterns = [
    path('chat_one_one/', ChatRoomView.as_view(), name="chatroom"),

    # API
    path("api/get_message/", get_message, name="get_message"),
    path("api/get_lazy_message/", get_lazy_message, name="get_lazy_message"),
    path("api/send_message/", send_message,name="send_message")
]

linemazzdemo/linemazzdemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chatroom.urls')),
    path('line/', include('linemessageapi.urls'))
]

linemazzdemo/chatroom/models.py
from django.db import models

# Create your models here.
from linemessageapi.models import LineAccounts, LineContact

class ChatSession(models.Model):
    token                   = models.CharField(max_length=1000, db_index=True, unique=True)
    line_account            = models.ForeignKey(LineAccounts, null=True, on_delete=models.SET_NULL)
    line_contact            = models.ForeignKey(LineContact, null=True, on_delete=models.SET_NULL)
    start_conversation_at   = models.DateTimeField(auto_now_add=True)
    end_conversation_at     = models.DateTimeField(blank=True, null=True)
    update_conversation_at  = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.token

class ChatMessage(models.Model):
    session         = models.ForeignKey(ChatSession, null=True, on_delete=models.SET_NULL)
    line_account    = models.ForeignKey(LineAccounts, null=True, on_delete=models.SET_NULL)
    line_contact    = models.ForeignKey(LineContact, null=True, on_delete=models.SET_NULL)
    message_type    = models.CharField(max_length=1000, db_index=True)
    text            = models.TextField(blank=True)
    image           = models.ImageField(blank=True, null=True, max_length=1000)
    file            = models.FileField(blank=True, null=True, max_length=1000)
    created_on      = models.DateTimeField(auto_now_add=True, db_index=True)
    is_read         = models.BooleanField(default=False)
    # is_push       = models.BooleanField(default=False, db_index=True)
    raw_data        = models.TextField(blank=True, null=True)
    status_coversation      = models.CharField(max_length=20, blank=True)
    
    def __str__(self):
        return "{} | {} | {}".format(self.line_contact, self.message_type, self.created_on)
    

linemazzdemo/chatroom/views.py
from django.shortcuts import render
from django.http import JsonResponse

from django.views import View

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from rest_framework.views import APIView
from rest_framework.response import Response

from .models import ChatSession, ChatMessage


class ChatRoomView(View):

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request):
        token = request.GET.get('token')
        session_list = ChatSession.objects.filter(token= token)
        if not session_list:
            return JsonResponse({"error": "dont have session"})
        session_list = session_list.filter(end_conversation_at=None)
        if not session_list:
            return JsonResponse({"error": "session is expire"})
        session_now = session_list.first()
        return render(request, 'chatroom/chatroom_.html', context= {"token": token})

linemazzdemo/chatroom/templates/chatroom/chatroom_.html
{% extends "base_.html" %}

{% block container %}
{% load static %}

<div class="col-md-3"></div>
<div class="col-md-6">
    <div class="row">
        <div id="monitor_chat" class="monitor_chat col-md-12">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 sent_message_chat">
            <div>count : <span id="count"></span></div>
            <div>time_last_message : <span id="show_last_time"></span></div>
            <!-- <div class="row">
                <div class="col-md-10">
                    <input for="send_button" class="col-md-12" type="text" name="" id="text_messages">
                </div>
                <div class="col-md-2">
                    <button id="send_button">
                        ส่ง
                    </button>
                </div>
            </div> -->
                <form>
                    
            <div class="row">
                    <div class="col-md-10">
                    <input class="col-md-12" type="text" name="" id="text_message">
                    </div>
                    <div class="col-md-2">  
                    <input type="submit" id="send_button" value="ส่งข้อความ">
                    </div>
                </div>
                </form>
        </div>
    </div>
</div>
<div class="col-md-3"></div>
{% endblock container %}

{% block script %}
<script>
    var count_message = 0
    var time_last_message = ""

    function show_test(){
        $('#show_last_time').html(time_last_message)
        $('#count').html(count_message)
    }

    function get_message(mode_usage) {
        if(mode_usage == "update"){
            url = `${window.location.origin}${"{% url "chat:get_message" %}"}?token={{ token }}&time_last=${ time_last_message }&mode_get_message=${ mode_usage }`
        }
        else if(mode_usage == "lazy"){
            url = `${window.location.origin}${"{% url "chat:get_lazy_message" %}"}?token={{ token }}&start_message=${count_message}`
        }
        else{
            url = `${window.location.origin}${"{% url "chat:get_message" %}"}?token={{ token }}`
        }        
        fetch(url).then(res => res.json())
            .then( result => {
                if('error' in result){
                    return
                }

                data = result["data"]
                var conversation_all = ""
                for (conversation of data){
                    if(conversation["message_type"] === "text"){
                        var message_content = conversation["message"]
                    }
                    else if(conversation["message_type"] === "img"){}
                    else if(conversation["message_type"] === "file"){}

                    var date_ = conversation["date_message"]
                    var display_name = conversation["display_name"]

                    if(conversation["status_conver"] == 0){
                        conversation_all += `
                        <div class="box_conversation_left">
                        <div class="contact_chat">${display_name}</div>
                        <div class="message_con"><p>${message_content}</p></div>
                        <div class="date_con">${date_}</div>                
                        </div >
                        `
                    }
                    else{
                        conversation_all += `
                        <div style="background-color: #FFE4C4;" class="box_conversation_right">
                            <div class="contact_chat">${display_name}</div>
                            <div class="message_con"><p>${message_content}</p></div>
                            <div class="date_con">${date_}</div>                
                        </div >
                        `
                    }  
                    count_message += 1
                    time_last_message = date_
                }
                show_test()
                if(mode_usage == "update"){
                    if(conversation_all == ""){
                        return
                    }
                    $("#monitor_chat").append(conversation_all)
                    
                    var objDiv = document.getElementById("monitor_chat");
                    objDiv.scrollTop = objDiv.scrollHeight;

                }else if(mode_usage == "lazy"){
                    $("#monitor_chat").prepend(conversation_all)

                }else{
                    $("#monitor_chat").html(conversation_all)

                    var objDiv = document.getElementById("monitor_chat");
                    objDiv.scrollTop = objDiv.scrollHeight;

                }
                conversation_all = ""

            })      

    } 
    
    function get_lazy_message(){
        url = `${window.location.origin}${"{% url "chat:get_lazy_message" %}"}?token={{ token }}&start_message=${count_message}`
        fetch(url).then(res => res.json()).then( result => {
        })
    }

    function use_function_get_update_message(){
        get_message("update")
    }
    function use_function_get_lazy_message(){
        // get_message("lazy")
    }

    $(document).ready(function() {
        get_message()
        setInterval(use_function_get_update_message, 1000);
        
        $("#monitor_chat").on('mousewheel', function(e){
            if(e.originalEvent.wheelDelta > 0 && this.scrollTop == 0){
                use_function_get_lazy_message()
            }
            else if($(this).innerHeight() + this.scrollTop >= this.scrollHeight - 2){   
                console.log($(this).innerHeight() + this.scrollTop, this.scrollHeight - 2)
            }
        })

    });
    
    $(document).on('click', '#send_button', function(e){
        e.preventDefault()

        let input_text = $('#text_message').val()
        if(input_text == ''){return}
        data = {
            message_type : "text",
            message : input_text
        }
        send_message(data)
        
    })

    function send_message(data){
        $('#text_message').val("")
        
        $("#send_button").attr('disabled', 'disabled');

        fetch(`${window.location.origin}${"{% url "chat:send_message" %}"}?token={{ token }}&start_message=${count_message}`, {
            method: 'POST',
            headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }).then(res => { 
            return res.json()}).then( result => {
            if('error' in result){
                alert(result["error"])
                return
            }
            
            $("#send_button").removeAttr("disabled");
                        
        })
    }


</script>
{% endblock script %}